name: twofold
description: A small utility for representing values with two possible outcomes, commonly failure or success.
version: 0.1.0
homepage: https://github.com/Wing-Works/twofold
repository: https://github.com/Wing-Works/twofold

topics:
  - error-handling
  - utility
  - functional
  - dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
